name: flutter_project_target
description: A new Flutter project.
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  encrypt: ^5.0.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  logger: ^2.2.0
  get_storage: ^2.1.1
  awesome_snackbar_content: ^0.1.3
  get_it: ^7.6.7
  go_router: ^13.2.1
  rxdart: ^0.27.7
  devicelocale: ^0.7.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  firebase_database: ^11.0.4
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  firebase_messaging: ^15.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  mockito: ^5.0.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true


